name: Daily Notifications

on:
  schedule:
    - cron: '40 22 * * *'  # À 22h40 tous les jours
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  trigger-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Notifications
        id: notify
        continue-on-error: true  # Continue même en cas d'erreur pour pouvoir notifier
        run: |
          echo "::group::Sending daily notifications"
          response=$(curl -s -w "\n%{http_code}" -X GET 'https://blog-starter-kit-git-main-aayachi328s-projects.vercel.app/api/notifications/daily')
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          echo "Response body: $body"
          echo "HTTP status code: $http_code"
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to send notifications. Status code: $http_code"
            echo "error_message=$body" >> $GITHUB_ENV
            exit 1
          fi
          echo "::endgroup::"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const errorMessage = process.env.error_message || 'Unknown error';
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '❌ Échec des notifications quotidiennes',
              body: `Les notifications quotidiennes ont échoué le ${new Date().toLocaleDateString('fr-FR')}.
              
              **Message d'erreur :**
              \`\`\`
              ${errorMessage}
              \`\`\`
              
              [Voir les logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            }); 